'use client'
import { useState } from 'react'

const places = [
  { name:'Maheshwar', state:'Madhya Pradesh', score:94, why:'Living heritage, riverfront calm and textile culture.', tags:'Heritage · Craft · River' },
  { name:'Chettinad', state:'Tamil Nadu', score:92, why:'Grand houses, distinctive cuisine and living craft traditions.', tags:'Architecture · Food · Culture' },
  { name:'Champaner–Pavagadh', state:'Gujarat', score:89, why:'A remarkable historic landscape with layers of architecture and pilgrimage.', tags:'Heritage · Landscape · History' },
]

export default function Explorer() {
  const [submitted, setSubmitted] = useState(false)
  const [days, setDays] = useState('4')
  const [style, setStyle] = useState('Heritage + local culture')
  if (submitted) return <main className="shell"><nav className="nav"><div className="brand">Travel Collector</div><div className="navlinks"><span>Explorer</span><span>My Journey</span><span>Passport</span></div></nav><section className="section"><div className="eyebrow">Explorer report · preliminary</div><h1 style={{fontSize:'clamp(58px,8vw,108px)'}}>Your India,<br/><i>considered.</i></h1><p className="muted" style={{fontSize:19,maxWidth:650}}>A first-pass recommendation based on your requirements. This is an Explorer report, not the final concierge itinerary. Every recommendation should ultimately be verified against the Bharat Atlas source record.</p><div className="section-head" style={{marginTop:70}}><h2 className="section-title">Your brief</h2><p className="muted">{days} days · {style}</p></div><div className="grid">{places.map(p=><article className="card" key={p.name}><div className="tag">{p.state} · Match {p.score}</div><h3>{p.name}</h3><div>{p.tags}</div></article>)}</div><section className="section" style={{padding:'80px 0 20px',border:0}}><div className="identity"><div><div className="eyebrow">Editorial recommendation</div><h2 className="section-title">Maheshwar<br/><i>at an unhurried pace.</i></h2><p className="muted" style={{marginTop:25}}>Stay close to the river. Spend an afternoon with the town’s textile tradition. Walk the ghats around sunset. Pair the heritage with one carefully chosen local meal and a maker-led experience.</p></div><div className="identity-box"><div className="eyebrow">Suggested 4-day rhythm</div><h3>River · Loom · Temple · Table</h3><ul><li>Day 1: Arrival, riverfront and heritage walk</li><li>Day 2: Weaving tradition and local makers</li><li>Day 3: Temples, nearby landscape and slow lunch</li><li>Day 4: Breakfast, final market visit and departure</li></ul></div></div></section><div className="identity-box" style={{marginTop:60}}><div className="eyebrow">Next layer</div><h3>Make this journey personal</h3><p className="muted">A concierge can now refine this report around exact dates, starting point, hotel style, mobility, dining preferences, occasion and the kind of heritage you want to experience.</p></div></section></main>
  return <main className="shell"><nav className="nav"><div className="brand">Travel Collector</div><div className="navlinks"><span>Explore</span><span>Explorer</span><span>Passport</span></div></nav><section className="section" style={{maxWidth:1000,margin:'0 auto'}}><div className="eyebrow">Explorer · discover your India</div><h1 style={{fontSize:'clamp(58px,8vw,108px)'}}>Tell us how<br/><i>you travel.</i></h1><p className="muted" style={{fontSize:20,maxWidth:650}}>Give us the shape of your journey. Explorer will turn it into a considered first report using the destination intelligence layer.</p><div className="identity-box" style={{marginTop:55}}><label className="eyebrow">How many days?</label><select value={days} onChange={e=>setDays(e.target.value)} style={{display:'block',width:'100%',padding:18,margin:'12px 0 30px',background:'#f5f1e9',border:'1px solid #aaa'}}><option>2</option><option>3</option><option>4</option><option>5</option><option>7</option><option>10</option></select><label className="eyebrow">What are you most drawn to?</label><select value={style} onChange={e=>setStyle(e.target.value)} style={{display:'block',width:'100%',padding:18,margin:'12px 0 30px',background:'#f5f1e9',border:'1px solid #aaa'}}><option>Heritage + local culture</option><option>Nature + slow travel</option><option>Food + craft</option><option>Architecture + history</option><option>Adventure + landscape</option></select><label className="eyebrow">What should the journey feel like?</label><div style={{font:'15px/1.7 Arial',marginTop:12}}>Unhurried · intimate · distinctive · locally rooted</div><button className="cta" onClick={()=>setSubmitted(true)}>Create my Explorer report</button></div></section></main>
}
